name: 'test remote port forward 2'

on:
  push:
    branches:
      - master

defaults:
  run:
    working-directory: test-cwd

jobs:
  test-remote-port-forward:
    permissions:
      id-token: write 
      contents: read  
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Configure AWS Credentials'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::398361073441:role/GithubAction-AssumeRoleWithAction 
          role-session-name: GitHubActions-RemotePortForward
          aws-region: us-west-2

      - name: 'Port Forward and Test MySQL Access'
        uses: abizer/aws-ssm-remote-port-forwarding-action@abizer-fixes
        with:
          target: i-0438c7a84ef72d148
          host: remote-pf-test.cluster-ctaq0o0wg3mj.us-west-2.rds.amazonaws.com
          port: 3306
          local-port: 3306

      - name: test
        run: |
          mysqladmin ping -h 127.0.0.1 -P 3306 --protocol=tcp -u admin -p 
